import { Calculator } from '@/store/useFinanceStore';
import {
  Banknote,
  Calculator as CalcIcon,
  Car,
  Coins,
  CreditCard,
  Globe,
  Home,
  LineChart,
  Percent,
  PiggyBank,
  Receipt,
  Wallet
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'loans', name: 'Loans', icon: CreditCard },
  { id: 'investments', name: 'Investments', icon: LineChart },
  { id: 'tax', name: 'Tax', icon: Receipt },
  { id: 'currency', name: 'Currency', icon: Globe },
  { id: 'banking', name: 'Banking', icon: Banknote },
  { id: 'business', name: 'Business', icon: CalcIcon },
  { id: 'insurance', name: 'Insurance', icon: Car },
  { id: 'real-estate', name: 'Real Estate', icon: Home },
  { id: 'salary', name: 'Salary', icon: Wallet },
  { id: 'cryptocurrency', name: 'Crypto', icon: Coins },
  { id: 'savings', name: 'Savings', icon: PiggyBank },
];

export const CALCULATORS: Calculator[] = [
  {
    id: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    category: 'loans',
    description: 'Calculate monthly mortgage payments including principal, interest, taxes, and insurance.',
    path: '/calculators/mortgage',
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    category: 'investments',
    description: 'Determine how your investments can grow over time with compound interest.',
    path: '/calculators/compound-interest',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    category: 'currency',
    description: 'Convert between different currencies using real-time exchange rates.',
    path: '/calculators/currency',
  },
  {
    id: 'salary-tax',
    name: 'Salary & Income Tax',
    category: 'tax',
    description: 'Estimate your take-home pay after taxes and deductions.',
    path: '/calculators/tax',
  },
  {
    id: 'auto-loan',
    name: 'Auto Loan',
    category: 'loans',
    description: 'Calculate monthly car loan payments and total interest.',
    path: '/calculators/auto-loan',
  },
  {
    id: 'roi-calculator',
    name: 'Return on Investment (ROI)',
    category: 'investments',
    description: 'Calculate the profit or loss on an investment.',
    path: '/calculators/roi',
  },
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    category: 'loans',
    description: 'Calculate your Equated Monthly Installment for loans.',
    path: '/calculators/emi',
  },
  {
    id: 'payment-calculator',
    name: 'Payment Calculator',
    category: 'loans',
    description: 'Calculate loan payments with options for extra payments.',
    path: '/calculators/payment',
  },
  {
    id: 'retirement-calculator',
    name: 'Retirement Calculator',
    category: 'savings',
    description: 'Plan your retirement nest egg.',
    path: '/calculators/retirement',
  },
  {
    id: 'savings-goal-calculator',
    name: 'Savings Goal Calculator',
    category: 'savings',
    description: 'Calculate required monthly savings to reach a target.',
    path: '/calculators/savings-goal',
  },
  {
    id: 'inflation-calculator',
    name: 'Inflation Calculator',
    category: 'investments',
    description: 'See how inflation impacts purchasing power.',
    path: '/calculators/inflation',
  },
  {
    id: 'rent-vs-buy',
    name: 'Rent vs. Buy',
    category: 'real-estate',
    description: 'Compare costs of renting vs. buying a home.',
    path: '/calculators/rent-vs-buy',
  },
  {
    id: 'net-worth',
    name: 'Net Worth',
    category: 'banking',
    description: 'Track your total assets and liabilities.',
    path: '/calculators/net-worth',
  },
  {
    id: 'emergency-savings',
    name: 'Emergency Savings',
    category: 'savings',
    description: 'Calculate your ideal emergency fund.',
    path: '/calculators/emergency-savings',
  },
  {
    id: 'debt-payoff',
    name: 'Debt Payoff',
    category: 'loans',
    description: 'Strategize faster debt repayment.',
    path: '/calculators/debt-payoff',
  },
  {
    id: 'college-savings',
    name: 'College Savings',
    category: 'savings',
    description: 'Plan for future education expenses.',
    path: '/calculators/college-savings',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'business',
    description: 'Convert between different units of measurement.',
    path: '/calculators/unit-converter',
  }
];
